### ISSUE TITLE
Latest docker image has a CVE  

### ISSUE THREAD

**Issue by Anton-Kartashev** [giantswarm/starboard-exporter#139]
Hello

I have install latest version, and found that image have a lot of CVE. Pleasem fix this.  

<img width="693" alt="Снимок экрана 2022-09-13 в 18 13 49" src="https://user-images.githubusercontent.com/13214410/189939796-af01e3a1-5c6e-4e11-8735-abc5aa14610e.png">

**Comment by stone-z** [comment]
Hey @Anton-Kartashev, these are fixed in [v0.6.0](https://github.com/giantswarm/starboard-exporter/blob/main/CHANGELOG.md#060---2022-09-16).
```
$ docker run --rm -it ghcr.io/aquasecurity/trivy:0.31.3 image quay.io/giantswarm/starboard-exporter:0.6.0 --quiet

quay.io/giantswarm/starboard-exporter:0.6.0 (debian 11.5)

Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```
