### ISSUE TITLE
Grafanadashboard yaml contains invalid json

### ISSUE THREAD

**Issue by NissesSenap** [giantswarm/starboard-exporter#28]
When trying to import the grafana json manually in to my grafana 7 instance i get error saying invalid json.
I get the same error when putting the pure json in a json reader.

I will see if I have time to try to find it on my own but if you already have a working edition in grafana it's probably enough to just export it out again.

**Comment by stone-z** [comment]
If not applying with helm, you'll have to un-template the legend override names in two spots:
https://github.com/giantswarm/starboard-exporter/blob/7a98fe982e82be07dc86db080be98e0b113df915/helm/starboard-exporter/templates/grafana-dashboard.yaml#L471
https://github.com/giantswarm/starboard-exporter/blob/7a98fe982e82be07dc86db080be98e0b113df915/helm/starboard-exporter/templates/grafana-dashboard.yaml#L552

**Comment by NissesSenap** [comment]
Ahh of course, thanks allot @stone-z
