### ISSUE TITLE
Add template to configure nodeSelector

### ISSUE THREAD

**Issue by dirsigler** [giantswarm/starboard-exporter#82]
Hello lovely GiantSwarm community,

I would need the ability to configure a [nodeSelector](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector).
Are there any objections to add them?

**Comment by stone-z** [comment]
Hi @dirsigler, that sounds fine to me. If you feel like doing a PR we'd be open to it, otherwise I'll plan to include this when we do the next release

**Comment by dirsigler** [comment]
Opened a PR to add it 🚀
