### ISSUE TITLE
Helm release v0.3.2 seems to be broken

### ISSUE THREAD

**Issue by elchenberg** [giantswarm/starboard-exporter#87]
Sorry for crossposting. I opened this issue at the giantswarm-catalog repository but I do not know if this was the correct place: https://github.com/giantswarm/giantswarm-catalog/issues/22

It seems to me that the Helm release v0.3.2 is broken because the values for the project's branch name and the commit hash are missing in the bundled release file.

**Comment by stone-z** [comment]
Hey @elchenberg you're absolutely right, thanks for notifying us. I'm working on the fix in https://github.com/giantswarm/starboard-exporter/pull/89 and will get a new release out shortly

**Comment by dirien** [comment]
HI @stone-z,

Just here to confirm the comment of @elchenberg.

We got this label

```yaml
app.giantswarm.io/branch: '[[ -Branch ]]'
app.giantswarm.io/commit: '[[ .SHA ]]'
```
on every resource. Looking forward for the patch. If you need any help, please let me know happy to help!

**Comment by stone-z** [comment]
[v0.3.3](https://github.com/giantswarm/starboard-exporter/releases/tag/v0.3.3) has been released :ship: sorry for any disruption, everyone.
A little context for those interested - We have two opinionated builders we use at Giant Swarm and I was hoping to get us closer to using ArtifactHub by switching to the other one, but it was intended for different types of projects and evidently still has a few wrinkles on this type of project. Thanks for letting us know!

**Comment by dirien** [comment]
Great thanks, @stone-z works like a charm and thanks for the swift fix!

```
app.giantswarm.io/branch: HEAD
app.giantswarm.io/commit: ce691c21f19d06ab45eaab2bc467135009aef8bc
app.kubernetes.io/instance: starboard-exporter
```

But the road to ArtifactHub is still possible?

**Comment by stone-z** [comment]
ArtifactHub is definitely still possible and on my radar. I just have to work out how to fit it into our existing deployment processes
